name: GitHub for IT Pro CI/CD Pipeline

on:
  workflow_dispatch:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]

jobs:
  # Deploy VM
  DeployVM:
    strategy:
      matrix:
        host: [ "20.56.48.191", "20.61.16.241", "20.61.16.244" ]
    runs-on: ubuntu-latest

    steps:
    # checkout code from repo
    - name: checkout repo
      uses: actions/checkout@v3
    
    - name: Pull From Git
      uses: appleboy/ssh-action@master
      with:
        host: ${{ matrix.host }}
        username: eitan
        key: ${{ secrets.VM_SSH_KEY }}
        script: cd ~/scripts && git reset --hard HEAD && git pull
    
    - name: Restart Fast API
      uses: appleboy/ssh-action@master
      with:
        host: ${{ matrix.host }}
        username: eitan
        key: ${{ secrets.VM_SSH_KEY }}
        script: sudo systemctl restart fileSaver
